blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :posts
  root 'posts#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  #root :to => "users#new"
  resources :users
  resources :sessions
  
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true, length: { in: 6..20 } , uniqueness: true
	validates :body, presence: true
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	
  protect_from_forgery with: :exception
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only:[:show, :edit, :update, :destroy]

  def index
  	@posts = Post.all.order("created_at DESC")
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)

  	if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end
  end

  def show
  	#@post = Post.find(params[:id])
  end

  def edit
  	#@post = Post.find(params[:id])
  end

  def update
  	#@post = Post.find(params[:id])

  	if @post.update(post_params)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post.destroy
  	redirect_to root_path
  end




  private

  def find_post
  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:title, :body)
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end
def create
	user = User.authenticate(params[:email], params[:password])
	if user
		session[:user_id] = user.id
		redirect_to root_url #,:notice => "Logged in!"
	else
	    flash.now.alert = "Invalid email or password"
	 render "new"
	end
end

def destroy
	session[:user_sid] = nil
	redirect_to root_url, :notice => "Logged out!"
end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	  @user = User.new
	end

	def create
	  #@user = User.new(params[:user])
	  @user = User.new(user_params)
	  if @user.save
	    redirect_to root_url, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end

	def user_params
    	params.require(:user).permit(:email, :password, :password_confirmation)
  	end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>header</h1>
<%= link_to "Home", root_path %>
<%= link_to "New Post", new_post_path %>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br><br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<%= f.submit %>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<% @post.errors.full_messages.each do |message| %>

<%= message %><br>

<%end%>
<hr>
<%= render 'form' %>

blog/app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<h1><%= post.title %></h1>
	<div>
		<p><%= truncate(post.body, :length => 250) %></p>
	</div>
	<%= link_to "Read Post", post %><br>
<% end %>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>
<% @post.errors.full_messages.each do |message| %>

<%= message %><br>

<%end%>
<hr>

<%= render 'form' %>

blog/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div>
	<p><%= @post.body %></p>
</div>

<%= link_to "Edit Post", edit_post_path(@post) %>
<%= link_to "Delete Post", post_path(@post), method: :delete, 
data: {confirm:"Are you sure"} %>

blog/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>